[general]
port = 5901
bind = [
    "10.254.251.210",
    "::"
]
database = "/home/alarm/nug.db"
log_level = "DEBUG"
name = "vnc-nug-server"
zeroconf = true
rtsp = "rtsp://192.168.40.1:8554"

[syslog]
ip = "127.0.0.1"
port = 1514

[[devices]]
ip = "192.168.40.100"
port = 5801
services = [ "pointer", "keyboard" ]

[[devices]]
ip = "192.168.40.117"
port = 5801
services = [ "video" ]
