[general]
port = 5901
bind = [
    "10.254.251.209",
    "::"
]
database = "/home/alarm/nug.db"
log_level = "DEBUG"
name = "vnc-nug-server"
zeroconf = true

[syslog]
ip = "127.0.0.1"
port = 1514

[[devices]]
ip = "192.168.40.147"
port = 5801
services = [ "mouse", "keyboard" ]

#[[devices]]
#ip = "10.0.0.2"
#port = 5002
#services = [ "video" ]
